language: C

before_install:
  - sudo add-apt-repository -y ppa:directhex/monoxide
  - sudo apt-get update

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

before_script:
  - xbuild /target:Travis CobaltAHK.proj

script:
  - nunit-console ./Tests/bin/Debug/Tests.dll
  - ./CobaltAHK-app/bin/Debug/CobaltAHK-app.exe test.ahk
